### ISSUE TITLE
Download image fail

### ISSUE THREAD

**Issue by skylark1848** [jarokelo/jarokelo2.0#16]
In gallery / preview of image, download option starts download but fails with Network Error.

**Comment by albertborsos** [comment]
works for me

**Comment by skylark1848** [comment]
![screen shot 2016-12-12 at 22 54 50](https://cloud.githubusercontent.com/assets/4942278/21120197/124b41c2-c0be-11e6-8e53-a2f7b8d21133.jpg)
https://jarokelo.hu/bejelentesek/budapest/16021/katyus-jarda 
mac chrome Version 54.0.2840.98 (64-bit)
:(

**Comment by albertborsos** [comment]
![kepernyofoto 2016-12-12 - 23 59 15](https://cloud.githubusercontent.com/assets/7307145/21120343/144ade7a-c0c7-11e6-81ed-0e9f04e2fa8b.png)
itt is az

**Comment by albertborsos** [comment]
adblock, tűzfal vagy valami más kiegészítő nem foghatja meg?

**Comment by skylark1848** [comment]
OK, it was the Mac OS Firewall...
