### ISSUE TITLE
Remove cat 23

### ISSUE THREAD

**Issue by skylark1848** [jarokelo/jarokelo2.0#19]
All public reports have been removed from cat = 23 "Iskolák és óvodák környéke"
https://jarokelo.hu/bejelentesek/*?category=23

Remove category from listings.
Urgency: users will start using it for random issues if we keep it there.

**Comment by robaganrab** [comment]
`views/report/create.php` invokes ...`dropDownList(ReportCategory::getList(), []`..., which does not checks for any "active" flag in the `report_category` table. The table itself was extracted by `migrations/m160711_093938_alter_table_report_change_category_type_to_integer.php`.

I don't see any quick solution to disable the category, but there is possibility to remove it from the database or filter it in the code every place where a user could find it.
The long term solution would be to apply a database change that removes it from the `report_category` table and moves any report in that category to a default other type.

**Comment by albertborsos** [comment]
i will fix it, give me some minutes

**Comment by albertborsos** [comment]
If it is urgent, I can deploy it soon to production. It just adds an `is_active` flag to `report_categories` and filters the inactive records.

**Comment by robaganrab** [comment]
@albertborsos thanks for the quick fix, it looks good for the above issue. Since you know better the code, could this change break something else somewhere else?

**Comment by albertborsos** [comment]
I checked the usages for this method. It will be OK.
